### ISSUE TITLE
API function to retrieve the total number of replies in a given comment?

### ISSUE THREAD

**Issue by babus** [danirus/django-comments-xtd#106]
Currently we can only count the replies one level down(immediate children). Is there any idea to implement to count the total replies to all the way down?

**Comment by danirus** [comment]
Good point. It shouldn't be too difficult. If you want to implement it go ahead. I can't look into it until at least mid September.

**Comment by babus** [comment]
I see, Thanks! If you have any quick ideas please pour it down which I can try with the implementation.

**Comment by babus** [comment]
What I think would be challenging is that a lot of db queries when we list the comments? Because for each comment we should fetch the count() in a recursive way? 

Tried all my best with level, order and thread_id, couldn't reach a solution. If each comment has been stored with a list of thread_id(list of parent ids) we can use the `__in` filter to annotate the counts.

**Comment by danirus** [comment]
Rewriting XtdComment's `tree_from_queryset` class method. You could annotate while reading the queryset to keep linear complexity, it doesn't require additional DB queries.

**Comment by tanveerahmad1517** [comment]
Please if you have any Ideas on this Topic Share with me i also need Facebook Comment and replies counting I want also count on replies on everything Please How can I do it?

**Comment by babus** [comment]
@tanveerahmad1517 I ended up recalculating the total replies and store it along with each comment. Can't find time to rewrite the class method as danirus suggested.

**Comment by rgutierrez-cotech** [comment]
@babus can you post some code detailing how you calculated the total replies? I know this is an old thread but I'm looking for this very thing and I'm stuck at the moment. I also tried using level, order, and thread_id but can't seem to come up with something.

On a related note, I'd also like to implement a `children()` method on a comment that returns all descendants of a comment, so that when I mark a comment as removed, I can also mark all its descendants as removed too. That way, when I do `{% get_comment_count %}` in my templates, I can skip over "orphaned" comments and get a more accurate count (at least for the type of comment feed implementation that we're working on)

**Comment by danirus** [comment]
Hi, any of you would like to review PR #217?
