### ISSUE TITLE
Like button will jump to the new page, how to change to modal mode?

### ISSUE THREAD

**Issue by HelloGit100** [danirus/django-comments-xtd#126]
When I click on the Like button, it will jump to the new page. How do I make this new page pop up on the current page in a modal way?

**Comment by danirus** [comment]
There's no such modal way. But you can use the ReactJS plugin, so that you can preview and post comments without leaving the page.

Read the tutorial [here](https://django-comments-xtd.readthedocs.io/en/latest/tutorial.html), there's a section in which I describe how to use the JavaScript plugin.

Also you can run the **comp** demo. There you will see two apps with comments: Articles and Quotes. Comments posted to Articles use the JavaScript plugin, while comments posted to Quotes use only the backend. To install the comp demo read the docs [here](https://django-comments-xtd.readthedocs.io/en/latest/example.html).

**Comment by HelloGit100** [comment]
@danirus Thank you!
