### ISSUE TITLE
Allow frontend editing of the comment?

### ISSUE THREAD

**Issue by erev0s** [danirus/django-comments-xtd#127]
Great work with this plugin, keep going !  
  
From what i saw i could not find if there is a possibility to allow the users to edit their comments. Is it possible?

**Comment by danirus** [comment]
Thanks @erev0s. I didn't implement that. 

Changing the text of a comment once it's posted might invalidate or make the comments that follow it loose their sense. However, there's a case that could allow changes, which on the other hand might be the most useful for the user, which is to change a comment just posted. If the comment is the last one in the thread, then changing the text wouldn't affect the following, because there are none yet.

Do you feel like implementing it?

**Comment by erev0s** [comment]
When I have some time over the next weeks I will look more closely to it as it seems an interesting feature.

**Comment by sandeepimpressads** [comment]
@erev0s have you started working on it ?
