### ISSUE TITLE
Buid javascript library

### ISSUE THREAD

**Issue by sandeepbalagopal09** [danirus/django-comments-xtd#139]
The tutorial shows how the javascript plugin can be integrated to a project. But when i try to do that getting an error from the console  'django is not defined'. I followed the doc, cloned the django-comments-xtd.git to my project folder. then did the build. After that copied the entire django_comments_xtd folder with the static assets to my project folder for django to recognise it as an app and load the static js. plugin-2.3.0.js and vendor~plugin-2.3.0.js. js files are load to my template but getting this error. How can i properly configure ?

**Comment by danirus** [comment]
Do you have the virtualenv active? The virtualenv where you did install Django?

**Comment by sandeepimpressads** [comment]
Its fixed now @danirus. I had to put the i18n urls and call the JavaScriptCatalog view.

**Comment by sandeepimpressads** [comment]
Getting another issue now. I am able to submit the comment but the list of comments showing under the article. getting this error 

> Invalid attempt to iterate non-iterable instance 
It is from create_tree(data) { method of commentbox.jsx

**Comment by sandeepimpressads** [comment]
Sorry for repopening, this is working but My server is taking lot of hits from the url jsi18n/ because the comments plugin is calling this url. Is it possible to not to get it from a url ? since the call is happening in my article detail page, whenever someone access the page, the url is called.So just one day I get around 30k+ hit on this url.

**Comment by danirus** [comment]
Does anyhow the solution for #144 fix this issue?

**Comment by sandeepimpressads** [comment]
Not actually.The call to django's javascript catalogue is still there. <script
  type="text/javascript"
  src="{% url 'javascript-catalog' %}"></script>

**Comment by danirus** [comment]
I will follow the [note on performance](https://docs.djangoproject.com/en/3.1/topics/i18n/translation/#note-on-performance) to fix this issue.

**Comment by danirus** [comment]
Hi @sandeepbalagopal09, the last part of this issue is not a problem that can be fixed from within a Django application. Serving the JavaScript catalog is the responsibility of the Django project in which you integrate the application. 

Check the link above, [note on performance](https://docs.djangoproject.com/en/3.1/topics/i18n/translation/#note-on-performance), and follow any of the recommendations. It seems the best one is based on [django-statici18n](https://django-statici18n.readthedocs.io/en/latest/).

**Comment by danirus** [comment]
My last answer pointed in the direction to solve this issue. Given that it's over 5 months since then I'm closing the issue. Please, don't hesitate to use the [Discussions](https://github.com/danirus/django-comments-xtd/discussions) if you need more help. Thanks!
