### ISSUE TITLE
render_xtdcomment_tree  not nested

### ISSUE THREAD

**Issue by keiser1080** [danirus/django-comments-xtd#143]
Hi,

is there a way to render_xtdcomment_tree  like render_comment_list,
in linear and not nested?

I like all the option shiped with django-comments-xtd. (like/dislike, gravatar, flag, repply ect...)
But for better readability i realy prefer the linear comment.

**Comment by danirus** [comment]
Hi @keiser1080,

You could use the setting [COMMENTS_XTD_MAX_THREAD_LEVEL](https://django-comments-xtd.readthedocs.io/en/latest/settings.html#comments-xtd-max-thread-level) to avoid nesting comments. Or if you have several models you want to post comments to, and need to allow nested comments for one and disable it for the others, you could use [COMMENTS_XTD_MAX_THREAD_LEVEL_BY_APP_MODEL](https://django-comments-xtd.readthedocs.io/en/latest/settings.html#comments-xtd-max-thread-level-by-app-model).

The [comp example site](https://github.com/danirus/django-comments-xtd/tree/master/example/comp) uses both in case you want to give it a try.

**Comment by keiser1080** [comment]
> Hi @keiser1080,
> 
> You could use the setting [COMMENTS_XTD_MAX_THREAD_LEVEL](https://django-comments-xtd.readthedocs.io/en/latest/settings.html#comments-xtd-max-thread-level) to avoid nesting comments. Or if you have several models you want to post comments to, and need to allow nested comments for one and disable it for the others, you could use [COMMENTS_XTD_MAX_THREAD_LEVEL_BY_APP_MODEL](https://django-comments-xtd.readthedocs.io/en/latest/settings.html#comments-xtd-max-thread-level-by-app-model).
> 
> The [comp example site](https://github.com/danirus/django-comments-xtd/tree/master/example/comp) uses both in case you want to give it a try.

thanks for your answer but i am losing the repply button when the  COMMENTS_XTD_MAX_THREAD_LEVEL = 0 .
I will try the complex example to check if it's also the case.

A good example of the what i try to do is the github issue, i can reply using a quote and you will be 
your comment will appear  on in the top of my comment and you will be notified

**Comment by danirus** [comment]
Yes, you loose the reply link under each comment because nested comments have been disabled by change the following setting:

    COMMENTS_XTD_MAX_THREAD_LEVEL = 0

To post the next comment the user has to use the one and only form available above the form. Or below, it depends on how you decide to use the templates and the tags.

> A good example of what I try to do ...

If you want to display quoted text you can achieve using Markdown. To automate such behaviour you will have to clone and modify the app. But that behaviour in my opinion won't work well. Bear in mind that once you have a few comments, the last comment in the list will contain all the comments. And so on up the list. Comments will be repeated all over the cascade of comments.

**Comment by keiser1080** [comment]
> If you want to display quoted text you can achieve using Markdown. To automate such behaviour you will have to clone and modify the app. 

Add the quoted comment are not really needed. But the owner of the comment where the repply is made have to be notified.

Do you think it's doable using django-comments-xtd with COMMENTS_XTD_MAX_THREAD_LEVEL = 0,

To have:
- comment owner notified in case of a repply.
- thread follow (user can suscribe to a thread)
- Like/dislike/ liked by/ comment report

Could you give some guidence to achive this?
correct me if i am wrong.
I think i have to create a new view based XtdCommentListView
and  to modify the django_comments_xtd/comment_list.html" to add the like/report/liked by
And to create a a set of querys:
- to get the comment filtred on the 
- to get the like flag & the user
- to get the comment followup

or maybe it's better to start with the django-comments & add missing fonctionality 
(I am new to djando)

**Comment by danirus** [comment]
It depends. Do you want to use the JavaScript plugin in the app? If so look at the [articles_detail.html](https://github.com/danirus/django-comments-xtd/blob/master/example/comp/templates/articles/article_detail.html) template of the comp demo site. Install it following [this instructions](https://django-comments-xtd.readthedocs.io/en/latest/example.html), change the `COMMENTS_XTD_MAX_THREAD_LEVEL` to `0` in the settings.py of the comp demo, also remove the `COMMENTS_XTD_MAX_THREAD_LEVEL_BY_APP_MODEL`. 

If you don't want the JavaScript plugin, look into the [quotes_detail.html](https://github.com/danirus/django-comments-xtd/blob/master/example/comp/templates/quotes/quote_detail.html). It also uses the `render_xtdcomment_tree` tag. The reason why I suggest you to use the xtdcomment tree is because you get the feedback buttons for free. 

Otherwise you could also implement all that as you suggest. You will then gain more control as you will learn how it works. In such a case it's worth following the Tutorial (I suppose you did already).

About your question on the follow-up: If you set up `COMMENTS_XTD_MAX_THREAD_LEVEL = 0`, email addresses that tick the follow-up box will receive notifications when there are new comments.

**Comment by keiser1080** [comment]
@danirus thanks for the support,
i will check asap

**Comment by SEGATON** [comment]
I followed the tutorial and the replies are not nested under comments. What can I do to fix this?

**Comment by danirus** [comment]
> I followed the tutorial and the replies are not nested under comments. What can I do to fix this?

@SEGATON, sorry that I didn't answer before. I answered you in the GitHub Discussion where you posted the question.
