### ISSUE TITLE
JavaScript plugin - big file size

### ISSUE THREAD

**Issue by sandeepimpressads** [danirus/django-comments-xtd#144]
The file vendor~plugin-2.4.3.js is 1.3 MB in size. After minifying it is 386.2KB. Is there any way to reduce the file size further ? It is costing dearly when put on s3.

**Comment by danirus** [comment]
You are right, I will change the build of the bundle to leave ReactJS out of the bundle. That will reduce a lot the size of the bundle.

**Comment by danirus** [comment]
@sandeepimpressads, the issue has been fixed in v2.5.0. I just released it.
Bear in mind that now you have to include the script tags to add React and ReactDOM in your HTML templates. I mean, include the following within your <model>_detail.html file: 

    <script crossorigin src="https://unpkg.com/react@16/umd/react.production.min.js"></script>
    <script crossorigin src="https://unpkg.com/react-dom@16/umd/react-dom.production.min.js"></script>

I updated [that part of the tutorial](https://django-comments-xtd.readthedocs.io/en/latest/tutorial.html#load-the-plugin) too.

**Comment by sandeepimpressads** [comment]
Thanks @danirus let me go through it.

**Comment by danirus** [comment]
@sandeepimpressads, feel free to reopen the issue if it's not resolved.

**Comment by sandeepimpressads** [comment]
This is resolved. Thanks.
