### ISSUE TITLE
Comment count not checking the is_removed flag

### ISSUE THREAD

**Issue by sandeepimpressads** [danirus/django-comments-xtd#148]
The total comment count shown above the comment box is seem to be returning the number of objects only. It is not taking into account the fact that some are removed.

**Comment by danirus** [comment]
You mention something posted above, but I guess you meant issue #145. Let's keep this report here as this is an actual bug, while issue #145 is an enhancement.
And thanks for your report!

**Comment by sandeepimpressads** [comment]
I am actually not yet sure whether its a bug. because the is_removed comments still appear in the article with the text "This comment has been removed". Is that why it is counted in the total number of comments ?

**Comment by danirus** [comment]
In the last version 2.5.1 I fixed the issue #138 regarding this in particular. So when you remove a comment (or you make is_public False), nested comments get is_public False too. If you use a version previous to 2.5.1, that logic is not happening.

**Comment by danirus** [comment]
Sorry, about your question: 
Yes, comments with is_public==True are counted, regardless of the value of is_removed.

**Comment by sandeepimpressads** [comment]
Okay. May i know why the comments with is_removed are still displaying and counted into the total ? My client is keep asking me this question. Is this the practice which is used generally in comments ?

**Comment by danirus** [comment]
That is the distinction between is_public and is_removed.

A removed comment is displayed but its content is not displayed (maybe because it was flagged inappropriate). People reading the comments might still want to see that the comment that was previously displayed and later flagged by several people as inappropriate now has been removed. But it was there before, therefore it's displayed in the tree, but the text is removed. This also tells visitors that comments are moderated.

You as a developer still has the chance to remove it altogether by using the is_public flag.

**Comment by sandeepimpressads** [comment]
thanks for the clarification. 

I was looking at the code added from #138 https://github.com/danirus/django-comments-xtd/blob/master/django_comments_xtd/models.py#L199 . Doesn't the publish_or_unpublish_on_pre_save function called on save of every model in the the project ? (Syntax like this `@receiver(post_save, sender=XtdComment)`) could be more better ? 

Also may i know why publish_or_unpublish_on_removal_flag and publish_or_unpublish_on_pre_save both are required ? the pre_save wouldn't call always ?

**Comment by danirus** [comment]
Sorry for the late reply, and thank you for your suggestions, you are right.
I'll change the code in the pull request #146. ;-)
