### ISSUE TITLE
How to customize xtd-comments framework?

### ISSUE THREAD

**Issue by okaysimon** [danirus/django-comments-xtd#24]
How to customize xtd-comments framework? For example, create a custom xtd-comment Model that adds on the “title” field.

I have tried following the steps in "Customizing the comments framework" of django-comments official manual, but it didn't work. https://docs.djangoproject.com/en/1.7/ref/contrib/comments/custom/

And I also tried writing a new model and form which is as same as XtdCommnet and XtdCommentForm besides adding a new field, and changing COMMENTS_XTD_FORM_CLASS and COMMENTS_XTD_MODEL in the setting file. But it didn't work neither.

Is there any chance to do that?

**Comment by danirus** [comment]
Hi @okaysimon, yes, you can do it in the same way as you would do it with the Django Comments Frakework, but there are a few details I didn't mention in the docs. You must have `COMMENTS_APP='django_comments_xtd`, and then use `COMMENTS_XTD_FORM_CLASS` and `COMMENTS_XTD_MODEL` to refer to your classes. Also, in your form class, be sure that the method get_comment_model returns TmpXtdComment, so that you urlize the new field in addition to the fields of `XtdComment`.
This answer comes too late, I'm very sorry. My apologies.

**Comment by danirus** [comment]
There is a new demo project that showcase how to extend the app. It's within the ``custom_comments`` directory inside ``django_comments_xtd/demos``. I hope it's useful for you.
I updated the documentation to cover it in [Customizing django-comments-xtd](http://pythonhosted.org/django-comments-xtd/extending.html).
