### ISSUE TITLE
Force moderation of a comment

### ISSUE THREAD

**Issue by Naddiseo** [danirus/django-comments-xtd#34]
I think I may be missing something obvious, but I can't seem to get a comment to be created with `is_public = False`,  and from what I can tell, the `_create_comment` function causes this by always setting the `is_public` to `True`. 

Is connecting to the `pre_save` signal the best way to accomplish this?

**Comment by danirus** [comment]
You are right, there's a bug when you moderate a comment. I fixed it a few months ago in the `develop` branch but didn't do the commit until a few minutes ago. The `develop` branch is unusable yet, so I'll port the fix to the master branch to make it available as soon as possible.

It doesn't have an easy solution. If `is_public` is `False`, follow-up notifications on this comment don't have to be sent. Also the response have to change so that instead of redirecting to a "comment has been posted, thank you", it has to say something like "your comment is being moderated". That change affect several functions in the views module, like `on_comment_was_posted`, `sent`, and `confirm`.

I'll try to implement the solution in the coming days.
@Naddiseo, thanks for reporting it.
