### ISSUE TITLE
Custom e-mail template possible?

### ISSUE THREAD

**Issue by sanastasiou** [danirus/django-comments-xtd#98]
@danirus is it possible to override the e-mail notification template?

We use a common template for all e-mails, so it would be nice if we could also use our own template for the comment notifications as well.

**Comment by danirus** [comment]
Yes, just override:
 * templates/django_comments_xtd/email_confirmation_request.html
 * templates/django_comments_xtd/email_confirmation_request.txt
 * templates/django_comments_xtd/email_followup_comment.html
 * templates/django_comments_xtd/email_followup_comment.txt

The txt version is required too. Both, html and txt, are sent in a multipart message, so that people reading text-only emails can see the message.
